name: Admin Workflow
on: 
    pull_request:
        branches:
            - auth-admin
            - main
    push:
        branches:
            - main
jobs:
    set-up-environment:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1

        - name: Flutter set up
          uses: subosito/flutter-action@v1
          with:
            flutter-version: 3.19

        - name: Navigate to Admin App
          run: cd "apps/admin"
          
        - name: Clean Build
          run: flutter clean
        
        - name: Getting Dependencies
          run: flutter pub get

        - name: Build Apk Release
          run: flutter build apk --split-per-abi
